USE [master]
GO
/****** Object:  Database [Banking_System]    Script Date: 1/16/2025 8:43:57 AM ******/
CREATE DATABASE [Banking_System]
GO
ALTER DATABASE [Banking_System] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banking_System].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Banking_System] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Banking_System] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Banking_System] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Banking_System] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Banking_System] SET ARITHABORT OFF 
GO
ALTER DATABASE [Banking_System] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Banking_System] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Banking_System] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Banking_System] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Banking_System] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Banking_System] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Banking_System] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Banking_System] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Banking_System] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Banking_System] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Banking_System] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Banking_System] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Banking_System] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Banking_System] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Banking_System] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Banking_System] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Banking_System] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Banking_System] SET RECOVERY FULL 
GO
ALTER DATABASE [Banking_System] SET  MULTI_USER 
GO
ALTER DATABASE [Banking_System] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Banking_System] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Banking_System] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Banking_System] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Banking_System] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Banking_System] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Banking_System', N'ON'
GO
ALTER DATABASE [Banking_System] SET QUERY_STORE = ON
GO
ALTER DATABASE [Banking_System] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Banking_System]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[FirstName] [varchar](10) NOT NULL,
	[LastName] [varchar](10) NOT NULL,
	[Phone] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChatConversation]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChatConversation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StaffId] [int] NULL,
	[CusId] [int] NULL,
	[DateCreate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChatMessage]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChatMessage](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConId] [int] NULL,
	[SenderType] [nvarchar](255) NOT NULL,
	[SenderId] [int] NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[DateCreate] [datetime] NULL,
	[IsRead] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Deposition]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deposition](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CusId] [int] NULL,
	[DateCreate] [datetime] NOT NULL,
	[Amount] [bigint] NOT NULL,
	[Status] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[History]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[History](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CusId] [int] NULL,
	[TransactionId] [int] NULL,
	[SavingId] [int] NULL,
	[LoanId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HistoryInformation]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HistoryInformation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HistoryId] [int] NULL,
	[ServiceType] [nvarchar](255) NOT NULL,
	[ServiceId] [int] NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[DateCreate] [datetime] NOT NULL,
	[Status] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loan]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loan](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CusId] [int] NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[DateExpired] [int] NULL,
	[Amount] [bigint] NOT NULL,
	[Status] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Saving]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Saving](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CusId] [int] NULL,
	[Amount] [bigint] NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[Rate] [decimal](10, 2) NOT NULL,
	[Status] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Staff]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Staff](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[FirstName] [varchar](10) NOT NULL,
	[LastName] [varchar](10) NOT NULL,
	[Phone] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](255) NOT NULL,
	[RoleId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transaction]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transaction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SenderId] [int] NULL,
	[ReceiverID] [int] NULL,
	[DateCreate] [datetime] NOT NULL,
	[Amount] [bigint] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[TotalAmount] [bigint] NOT NULL,
	[Status] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Wallet]    Script Date: 1/16/2025 8:43:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Wallet](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CusId] [int] NULL,
	[Amount] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChatMessage] ADD  DEFAULT (getdate()) FOR [DateCreate]
GO
ALTER TABLE [dbo].[ChatMessage] ADD  DEFAULT ((0)) FOR [IsRead]
GO
ALTER TABLE [dbo].[Deposition] ADD  DEFAULT (getdate()) FOR [DateCreate]
GO
ALTER TABLE [dbo].[HistoryInformation] ADD  DEFAULT (getdate()) FOR [DateCreate]
GO
ALTER TABLE [dbo].[Loan] ADD  DEFAULT (getdate()) FOR [StartDate]
GO
ALTER TABLE [dbo].[Saving] ADD  DEFAULT (getdate()) FOR [StartDate]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT (getdate()) FOR [DateCreate]
GO
ALTER TABLE [dbo].[ChatConversation]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[ChatConversation]  WITH CHECK ADD FOREIGN KEY([StaffId])
REFERENCES [dbo].[Staff] ([Id])
GO
ALTER TABLE [dbo].[ChatMessage]  WITH CHECK ADD FOREIGN KEY([ConId])
REFERENCES [dbo].[ChatConversation] ([Id])
GO
ALTER TABLE [dbo].[Deposition]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD FOREIGN KEY([LoanId])
REFERENCES [dbo].[Loan] ([Id])
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD FOREIGN KEY([SavingId])
REFERENCES [dbo].[Saving] ([Id])
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD FOREIGN KEY([TransactionId])
REFERENCES [dbo].[Transaction] ([Id])
GO
ALTER TABLE [dbo].[HistoryInformation]  WITH CHECK ADD FOREIGN KEY([HistoryId])
REFERENCES [dbo].[History] ([Id])
GO
ALTER TABLE [dbo].[Loan]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Saving]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Staff]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD FOREIGN KEY([ReceiverID])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD FOREIGN KEY([SenderId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Wallet]  WITH CHECK ADD FOREIGN KEY([CusId])
REFERENCES [dbo].[Customer] ([Id])
GO
USE [master]
GO
ALTER DATABASE [Banking_System] SET  READ_WRITE 
GO
